const RESERVATION_STATUS_PENDING = "pending";
const RESERVATION_STATUS_APPROVED = "approved";
const RESERVATION_STATUS_PAID = "paid";
const RESERVATION_STATUS_PICKED_UP = "picked_up";
const RESERVATION_STATUS_RETURNED = "returned";
const RESERVATION_STATUS_REJECTED = "rejected";

const LEGACY_RESERVATION_STATUS_PENDING = "Čeká na potvrzení";
const LEGACY_RESERVATION_STATUS_APPROVED = "Čeká na platbu";
const LEGACY_RESERVATION_STATUS_PAID = "Zaplaceno";
const LEGACY_RESERVATION_STATUS_PICKED_UP = "Vyzvednuto";
const LEGACY_RESERVATION_STATUS_RETURNED = "Vráceno";
const LEGACY_RESERVATION_STATUS_REJECTED = "Odmítnuto";

function normalizeReservationStatus(status) {
  const normalizedStatus = String(status || "").trim();

  const statusMap = {
    [LEGACY_RESERVATION_STATUS_PENDING]: RESERVATION_STATUS_PENDING,
    [LEGACY_RESERVATION_STATUS_APPROVED]: RESERVATION_STATUS_APPROVED,
    [LEGACY_RESERVATION_STATUS_PAID]: RESERVATION_STATUS_PAID,
    [LEGACY_RESERVATION_STATUS_PICKED_UP]: RESERVATION_STATUS_PICKED_UP,
    [LEGACY_RESERVATION_STATUS_RETURNED]: RESERVATION_STATUS_RETURNED,
    [LEGACY_RESERVATION_STATUS_REJECTED]: RESERVATION_STATUS_REJECTED
  };

  return statusMap[normalizedStatus] || normalizedStatus;
}